apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - nginx
    labelSelectors:
      "app": "nginx"
  duration: "80s"
  delay:
    latency: 50ms
  duration: "60s"