apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: my-network-delayv2
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - network-chaos
    labelSelectors:
      app: httpd
  delay:
    latency: 2s
  direction: to
  target:
    selector:
      namespaces:
        - default
      labelSelectors:
        app: nginx
    mode: one
  duration: "90s"
