apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: my-network-delayv3
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - nginx
  delay:
    latency: 500ms
  direction: to
  externalTargets:
    - "172.17.0.6"
    - "172.17.0.8"
    - "172.17.0.4"
  duration: "30s"
