apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partitionv2
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - nginx
    labelSelectors:
      "app": "nginx"
  direction: to
  target:
    selector:
      namespaces:
        - network-chaos
      labelSelectors:
        "app": "httpd"
    mode: all
  duration: "80s"
