kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: chaos-killv4
  namespace: pod-kill
spec:
  selector:
    namespaces:
      - pod-kill
    labelSelectors:
      app: nginx
  mode: all
  action: pod-kill
  duration: 150s
  gracePeriod: 0
